### ISSUE TITLE
Issue with wad2bin

### ISSUE THREAD

**Issue by TheDarkX-rises** [DarkMatterCore/wad2bin#3] opened 2020-08-16 02:58 UTC
Every time I tried to use the app with Rockband 3 DLCs in wad format, I got this error

###############################################################################################
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py:937: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\TheDarkX\Desktop\wad2bin\gui.py", line 518, in execute_script
    p = subprocess.Popen(args,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\TheDarkX\Desktop\wad2bin\gui.py", line 518, in execute_script
    p = subprocess.Popen(args,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\TheDarkX\Desktop\wad2bin\gui.py", line 518, in execute_script
    p = subprocess.Popen(args,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\TheDarkX\Desktop\wad2bin\gui.py", line 518, in execute_script
    p = subprocess.Popen(args,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\TheDarkX\Desktop\wad2bin\gui.py", line 518, in execute_script
    p = subprocess.Popen(args,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\TheDarkX\Desktop\wad2bin\gui.py", line 518, in execute_script
    p = subprocess.Popen(args,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\TheDarkX\Desktop\wad2bin\gui.py", line 518, in execute_script
    p = subprocess.Popen(args,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\TheDarkX\Desktop\wad2bin\gui.py", line 518, in execute_script
    p = subprocess.Popen(args,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\TheDarkX\Desktop\wad2bin\gui.py", line 518, in execute_script
    p = subprocess.Popen(args,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.193.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

I don't know if I made something wrong, or there's something that I don't know about this process

**Comment by DarkMatterCore** [comment] 2020-09-03 06:51
Seems like this is an issue with the graphical Python frontend. Thanks for reporting this issue.

@LyfeOnEdge Could you please check this issue?

**Comment by dippyshere** [comment] 2021-04-13 08:07
This problem is caused by the GUI py script (line 405), where it expects wad2bin to be named that and nothing else
`script = os.path.realpath("wad2bin.exe")`

The solution to this problem is to either rename the wad2bin binary that you downloaded to **exactly** `wad2bin.exe`, instead of `wad2bin-windows-x64.exe` or `wad2bin-windows-x86.exe`.

as for the python file, the fix for this would be to check if wad2bin or its default binary name variants exist, and tell the user if it doesn't exist to rename the exe.

**Comment by DarkMatterCore** [comment] 2021-06-01 21:38
Fixed in fabda9c6575afdc6c03bac903ac9c3c1dc0fc9bf.

**Closed by DarkMatterCore** 2021-06-01 21:38 UTC
Labels: bug
